import "./globals.css";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { Container, Theme } from "@radix-ui/themes";
import dynamic from "next/dynamic";

const NavBar = dynamic(() => import("./nav-bar"));
const AuthProvider = dynamic(() => import("./auth/provider"));
const QueryClientProvider = dynamic(() => import("./query-provider"));

// Font files can be collocated inside of `app`
const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "What's The Issue",
  description: "Generated by Arslan Ali",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <QueryClientProvider>
          <AuthProvider>
            <Theme accentColor="violet">
              <NavBar />
              <main className="p-5">
                <Container>{children}</Container>
              </main>
            </Theme>
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
